-- BE-INCR-FIXED-ASSETS PR-5 (nó C8; BRIEF itens 20-21; F-FA12 → a). F-FA14 → (b): migração PRÓPRIA
-- deste PR (execution-plan §1) — só a coluna que o Passo 26/27 de fato consome (o rascunho do item
-- 22/28, com `sourceItemRef` + `@@unique([payableId, sourceItemRef])`, NÃO está nesta migração:
-- achado durante a implementação — `createDraftFromPayable` precisa de `annualRateBp` NOT NULL no
-- `FixedAsset` e nem o BRIEF nem o ADR dizem de onde ele vem para um rascunho nascido de NF-e; ver
-- retorno desta sessão. Migração aditiva, `ADD COLUMN` simples (nullable, sem FK) — não força
-- rebuild no SQLite (mesma razão de `inventoryMultiItem`).
--
-- Memória migracao-sqlite-nao-e-transacional: prólogo idempotente — coluna já existente (rerun) não
-- quebra porque o Prisma emite isto uma única vez por deploy; documentado aqui por disciplina do
-- padrão do módulo, não porque este ADD COLUMN precise de IF NOT EXISTS (SQLite não suporta a
-- cláusula em ADD COLUMN; um rerun após falha PARCIAL desta migração de 1 statement só reaplicaria
-- se o commit anterior não tiver ocorrido — não há ponto intermediário a proteger aqui).
ALTER TABLE "payables" ADD COLUMN "fixedAssetItems" TEXT;
